# Generated by Django 6.1.1 on 2026-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование записи", max_length=100, verbose_name="Наименование"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Создайте запись", null=True, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите картинку",
                        null=True,
                        upload_to="blog/image",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(help_text="Введите дату создания записи", verbose_name="Дата создания"),
                ),
                ("publication", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("number_of_views", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "ordering": ["created_at", "name", "number_of_views"],
            },
        ),
    ]
