# Generated by Django 6.1.1 on 2026-10-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Опишите суть категории товаров', null=True, verbose_name='Характеристика категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(help_text='Загрузите картинку', upload_to='catalog/images', verbose_name='Изображение')),
                ('price_per_purchase', models.DecimalField(decimal_places=2, help_text='Укажите цену за одну покупку', max_digits=5)),
                ('created_at', models.DateField(help_text='Введите дату изготовления товара', verbose_name='Дата изготовления')),
                ('updated_at', models.DateField(help_text='Введите дату последнего изменения товара', verbose_name='Дата последнего изменения')),
                ('description', models.TextField(blank=True, help_text='Введите подробное описание товара.', null=True, verbose_name='Описание товара')),
                ('category', models.ForeignKey(help_text='Введите категорию товара', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name', 'price_per_purchase'],
            },
        ),
    ]
