# Generated by Django 6.1.1 on 2026-10-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "price"], "verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price_per_purchase",
            new_name="price",
        ),
    ]
