# Generated by Django 6.1.1 on 2026-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку",
                null=True,
                upload_to="catalog/images",
                verbose_name="Изображение",
            ),
        ),
    ]
